apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fitness-mongo-pvc
  namespace: gateway-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7Gi
  storageClassName: nfs-storage-class
